import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        {/* Grid - START */}
        <div className="grid grid-cols-5 gap-4">
          {/* Job - START */}
          <div className="container-result col-span-4">Job</div>
          {/* Job - END */}
          {/* Sidebar - START */}
          <div className="container-filter col-span-1">DAO Info</div>
          {/* Sidebar - END */}
        </div>
        {/* Grid - END */}
      </main>
    </div>
  )
}
