import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Header } from '../components/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto">
        {/* Header - START */}
        <Header />
        {/* Header - END */}
        {/* Grid - START */}
        <div className="grid grid-cols-5 gap-4">
          {/* Filter - START */}
          <div className="container-filter col-span-1">Filters</div>
          {/* Filter - END */}
          {/* Filter Results - START */}
          <main className="container-result col-span-3">
            {/* Result - START */}
            <div className="w-full border border-gray-100 rounded-sm shadow-sm">
              <div className="px-4 py-2">
                <div className="result-title">
                  <Link href="#">
                    <a>
                      <h2 className="text-lg font-medium">
                        Looking for a graphics desginer for our new NFT
                      </h2>
                    </a>
                  </Link>
                </div>
                <div className="result-org">
                  <h3 className="text-sm">buildspace</h3>
                </div>
                <div className="mt-3">
                  <div className="result-tag">
                    <div className="flex justify-start gap-1">
                      <div>
                        <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-gray-100 text-gray-800">
                          Badge
                        </span>
                      </div>
                      <div>
                        <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-gray-100 text-gray-800">
                          Badge
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* Result - END */}
          </main>
          {/* Filter Results - END */}
          {/* Sidebar - START */}
          <div className="container-result col-span-1">Sidebar</div>
          {/* Sidebar - END */}
        </div>
        {/* Grid - END */}
      </div>
    </>
  )
}
